(in-package #:nabla.iree.tests)
(REGRESSION-CASE :NAME JIT-DTYPE/F64-TRANSCENDENTALS-MATCH-EAGER :DATUM
                 "(#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE (1) :DTYPE :F64) 0)"
                 :TIMESTAMP 3999598358)
