(in-package #:nabla.tests)
(REGRESSION-CASE :NAME PRIMITIVES/DIV/SELF-IS-ONE-FOR-POSITIVE :DATUM
                 "(#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE (1 1 1) :DTYPE :F32) 0)"
                 :TIMESTAMP 3999467116)
