(in-package #:nabla.tests)
(REGRESSION-CASE :NAME PRIMITIVES/DIV/EAGER-MATCHES-REFERENCE :DATUM
                 "(#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE (1 1 1 1) :DTYPE :BF16) 0)"
                 :TIMESTAMP 3999467116)
(REGRESSION-CASE :NAME PRIMITIVES/DIV/EAGER-MATCHES-REFERENCE :DATUM
                 "(#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE (1 3 5 1) :DTYPE :F16) 1532899613)"
                 :TIMESTAMP 3999467262)
