(in-package #:nabla.tests)
(REGRESSION-CASE :NAME PRIMITIVES/MUL/BY-ONES-IS-IDENTITY :DATUM
                 "#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE NIL :DTYPE :BF16)"
                 :TIMESTAMP 3999467116)
