(in-package #:nabla.tests)
(REGRESSION-CASE :NAME PRIMITIVES/SUB/EAGER-MATCHES-REFERENCE :DATUM
                 "(#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE NIL :DTYPE :BF16) 852790872)"
                 :TIMESTAMP 3999467116)
