(in-package #:nabla.tests)
(REGRESSION-CASE :NAME PRIMITIVES/SUB/SELF-IS-ZERO :DATUM
                 "(#S(NABLA.TESTS.SUPPORT::ARRAY-SPEC% :SHAPE NIL :DTYPE :F32) 0)"
                 :TIMESTAMP 3999467116)
