(in-package #:nabla.tests)
(REGRESSION-CASE :NAME VMAP-CONTROL/WHILE-WITH-BATCHED-PRED-MATCHES-REFERENCE
                 :DATUM "(1 0 0 92)" :TIMESTAMP 4000002084)
(REGRESSION-CASE :NAME VMAP-CONTROL/WHILE-WITH-COND-IN-BODY-MATCHES-REFERENCE
                 :DATUM "(1 0 0 0)" :TIMESTAMP 4000002084)
(REGRESSION-CASE :NAME
                 VMAP-CONTROL/NESTED-VMAP-OF-WHILE-WITH-COND-MATCHES-REFERENCE
                 :DATUM "(1 1 0)" :TIMESTAMP 4000002084)
